# using docker for developing with Windows is not recommended

version: "3.9"
services:
  frontend:
    build: ./fe
    ports:
      - "${FE_PORT_OUTGOING}:${FE_PORT_INCOMING}"
    volumes:
      - ./fe:/app
    command: ["npm", "start"]
    depends_on:
      - backend

  backend:
    build: ./be
    ports:
      - "${BE_PORT_OUTGOING}:${BE_PORT_INCOMING}"
    volumes:
      - ./be:/app
    command: ["npm", "run", "dev"]
